esphome:
  name: liczniki-wody19

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "KEyTOyvZF0x8vbF1tLoGIj7mZYTKRACVTgvQJKT+/A0="

ota:
  - platform: esphome
    password: "3a121cdbe8d8169c3abcaf0958885d21"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.0.78
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.0.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Liczniki-Wody19 Fallback Hotspot"
    password: "12345678"

captive_portal:

external_components:
  - source: github://SzczepanLeon/esphome-components@3.2.3
    components: [ wmbus ]

time:
  - platform: sntp
    id: time_sntp

wmbus:
  mosi_pin: GPIO13
  miso_pin: GPIO12
  clk_pin:  GPIO14
  cs_pin:   GPIO15
  gdo0_pin: GPIO4
  gdo2_pin: GPIO5

 # led_pin: GPIO0
 # led_blink_time: "1s"

sensor:
    # int ApatorID = 0x4632337;
  - platform: wmbus
    meter_id: 0x4632337
    type: apator162
    key: "00000000000000000000000000000000"
    add_prefix: false
    #lqi:
    #  name: "LQI ciepla"
    rssi:
      name: "RSSI ciepla"
    total_water_m3:
      name: "Wodomierz_ciepla"
      force_update: true
    # int ApatorID = 0x4441230;
  - platform: wmbus
    meter_id: 0x4441230
    type: apator162
    key: "00000000000000000000000000000000"
    add_prefix: false
    #lqi:
    #  name: "LQI zimna"
    rssi:
      name: "RSSI zimna"
    total_water_m3:
      name: "Wodomierz_zimna"
      force_update: true
  # Serwer with a statistic data and OTA board update
web_server:
  port: 80
  ota: false
# Device functions:
switch:
  - platform: restart
    name: "_Reboot"
    
